### ISSUE TITLE
Blank histogram/no messages displayed; index growing

### ISSUE THREAD

**Issue by jakegibbonsdev** [lephisto/pfsense-graylog#50]
Hello,

I am not seeing data in streams messages in Graylog. I have followed the video and the guide at https://github.com/lephisto/pfsense-analytics/tree/master. I have checked for the flow of messages. what steps can I use to troubleshoot?

I have verified that data is flowing from the pfsense box to the vm port 5442. I can see the message count fluctuate under graylog/streams > pfsense, but when I click on the stream I see a blank histogram for message count as well as no messages. There is no data displayed in Grafana. The elasticsearch pfsense_0 has thousands of docs and is steadily growing. I have rebuilt a new vm since you updated the repo earlier today. Everything works up to step 6/Check Graylog.

Graylog Streams e.g. 17 messages/second. Must match all of the 2 configured stream rules.
Graylog Index e.g. pfsense-logs 1 index, 33,114 documents, 8.8MiB 

pfsense filter.log extract
Feb 21 17:39:55 remote filterlog[35405]: 76,,,100000101,re0,match,pass,in  ...
Feb 21 17:39:55 remote filterlog[35405]: 76,,,100000101,re0,match,pass,in  ...
Feb 21 17:39:55 remote filterlog[35405]: 4,,,1000000003,re0,match,block,in ...

Jake

**Comment by lephisto** [comment]
Browser issue? Timezone issue?

**Comment by jakegibbonsdev** [comment]
Looks like it is the timezone. The graylog container has a timezone of Etc/UTC. Everything else is America/Toronto. How do I make the container America/Toronto? I have already set the graylog.env variable
graylog.env:GRAYLOG_TIMEZONE=America/Toronto

**Comment by jakegibbonsdev** [comment]
The admin user in Graylog is set as UTC. Tried creating another admin to update the _admin_ timezone, but to no avail. Tried viewing the stream from the _new_ admin user with the correct timezone, but the histogram is still blank.

**Comment by jakegibbonsdev** [comment]
Solved:
Step 1, modify graylog/Dockerfile by adding the following before the USER graylog
```
ENV TZ={Your Timezone Here}
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
```

Step 2. modify graylog.env by adding 
`GRAYLOG_ROOT_TIMEZONE={Your Timezone Here}`
