### ISSUE TITLE
The last commit is breaking kabana

### ISSUE THREAD

**Issue by nandonov** [lephisto/pfsense-graylog#53]
Hi lephisto,

First of all, thanks for the work you are putting in this project, it makes me reconsider using pfpsense as my home firewall (used untangle up until now). Your effort is really appreciated.

Now, on the topic, I saw an issue while I am starting the containers as the kabana is exiting right away and there is no way to start it. After looking on the doker compose file, I saw you added a line to disable Kabana, I saw that this is something we can do while everything is up and running and we do not need Kabana at that point. Here is the commit, line 63 was the one causing the issue:

commit dc2fcd823ce6ed5a48b9a86b9b2133c4dfa853bb

I think we should probably have instructions on the README regarding this portion, but it is better if we comment this portion for those who try to setup the whole thing.

Again, thanks for your time on this project!

Have a nice one!

Nikolay

**Comment by nandonov** [comment]
Sorry, forgot to mention, graylog is unaccessble while Kibana is not running, that's the main reason I opened this ticket.

**Comment by SmoothBrainIT** [comment]
@nandonov is there a work around for getting Kibana up and running in order to access graylog?

**Comment by nandonov** [comment]
@t-jones14, yes, just comment the line:

cd pfsense-analytics/
cd ./Docker/
vim docker-compose.yml

![image](https://user-images.githubusercontent.com/21279807/113659337-cd9bad00-966f-11eb-8c90-ff47df1057d9.png)

**Comment by SmoothBrainIT** [comment]
@nandonov Perfect. Thank you.

**Comment by lephisto** [comment]
This is by intention, since Kibana is not needed for the Stack and I just wanted to include it for conveience in case someone needs a dataexploration tool.

**Comment by nandonov** [comment]
Thanks for the replay @lephisto. I saw the explanation on the notes, but for some reason this was impacting the graylog implementation. I had access to the web interface but there was an error and could not login. Maybe I did something wrong, it is possible, I wiped out everything and cannot reproduce right now. Feel free to close the ticket.
