### ISSUE TITLE
Can't run RUN chmod +x /etc/graylog/server/getGeo.sh

### ISSUE THREAD

**Issue by UffTec** [lephisto/pfsense-graylog#54]
Hello,

is anyone experiencing the same issue when running the 5/6 step?

`Step 5/6 : RUN chmod +x /etc/graylog/server/getGeo.sh && /etc/graylog/server/getGeo.sh
 ---> Running in b30dbe5bac10
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    20  100    20    0     0    112      0 --:--:-- --:--:-- --:--:--   112

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
ERROR: Service 'graylog' failed to build: The command '/bin/sh -c chmod +x /etc/graylog/server/getGeo.sh && /etc/graylog/server/getGeo.sh' returned a non-zero code: 2`

Thanks.

**Comment by netermin** [comment]
Tengo el mismo problema :(

**Comment by netermin** [comment]
Por favor podrían ayudarnos con una solución

**Comment by netermin** [comment]
I found the solution, you have to edit the getGeo.sh to place the license
